CREATE TABLE `church_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`church_name` varchar(255) NOT NULL,
	`denomination` varchar(255),
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(100),
	`zip_code` varchar(20),
	`country` varchar(100) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`email` varchar(320) NOT NULL,
	`website` varchar(500),
	`contact_name` varchar(255) NOT NULL,
	`contact_title` varchar(100),
	`contact_phone` varchar(50) NOT NULL,
	`contact_email` varchar(320) NOT NULL,
	`mission_statement` text,
	`vision_statement` text,
	`statement_of_faith` text,
	`church_history` text,
	`service_times` text,
	`ministries` text,
	`has_existing_website` boolean DEFAULT false,
	`existing_website_url` varchar(500),
	`desired_features` text,
	`preferred_colors` varchar(255),
	`additional_notes` text,
	`budget` varchar(100),
	`timeline` varchar(100),
	`status` enum('pending','in_progress','completed','cancelled') NOT NULL DEFAULT 'pending',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `church_submissions_id` PRIMARY KEY(`id`)
);
